#Messages
earned-sponge: "&6You earned &#dfff00{amount} sponges &6from the challenge! &eThey have been deposited into your bank! &6/bank"
did-not-meet-score: "&7You did not reach the required score of &4{amount} &7and did not receive any sponge!"