#Messages
earned-sponge: "&6You earned &#dfff00{amount} sponges &6from the challenge! &eThey have been deposited into your bank! &6/bank"
did-not-meet-score: "&7You did not reach the required score of &4{amount} &7and did not receive any sponge!"
left-the-game: "&4{player} &#EF9A9Aleft the game and will be removed from the challenge!"
challenge-cancelled: "&4The challenge will be cancelled due to no participants."
player-vote: "&#AB56B6{player} &#7E57C2voted for &#AB56B6{challenge}"
not-enough-players: "&#EF9A9ANot enough players voted for an event! Trying again in 10 minutes."
challenge-won-vote: "{challenge} &dhas won the vote!"
did-not-vote: "&#EF9A9AYou did not vote for the challenge and will not participate."
time-expired: "&7The voting time has expired and the event will start in 3 minutes!"
