api-version: 1.20
name: OVChallenges
version: 1.0
author: OVClub
main: org.ovclub.ovchallenges.Plugin
description: OVChallenges Commands
commands:
    challenges:
        description: Use OVChallenges
        aliases: [chal, ch, challenges]
        usage: /challenges
permissions:
    challenges.player.*:
        description: Access to OVChallenges
        default: true